services:
  api:
    build:
      context: .
      target: dev
    container_name: video_orchestrator
    volumes:
      - ./:/go/src/video-orchestrator
      - /var/www/html/streams:/var/www/html/streams
      - /var/www/html/uploads:/var/www/html/uploads
    env_file:
      - configuration/env/dev.env
      - .env
    ports:
      - "8181:8181"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:18-alpine
    container_name: video_db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    logging:
      options:
        max-size: 10m
        max-file: "10"
    ports:
      - "${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_NICE
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: