// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const getJobByID = `-- name: GetJobByID :one
SELECT id FROM video_jobs WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const lockAndMarkProcessing = `-- name: LockAndMarkProcessing :many
WITH jobs AS (
  SELECT id
  FROM video_jobs
  WHERE status = 'PENDING'
  ORDER BY created_at
  LIMIT $1
  FOR UPDATE SKIP LOCKED
        )
UPDATE video_jobs
SET status = 'PROCESSING',
    updated_at = now()
WHERE id IN (SELECT id FROM jobs)
  RETURNING id, filename, retry_count
`

type LockAndMarkProcessingRow struct {
	ID         int64
	Filename   string
	RetryCount int32
}

func (q *Queries) LockAndMarkProcessing(ctx context.Context, limit int64) ([]LockAndMarkProcessingRow, error) {
	rows, err := q.db.Query(ctx, lockAndMarkProcessing, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockAndMarkProcessingRow
	for rows.Next() {
		var i LockAndMarkProcessingRow
		if err := rows.Scan(&i.ID, &i.Filename, &i.RetryCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDone = `-- name: MarkDone :exec
UPDATE video_jobs
SET status = 'DONE',
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkDone(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markDone, id)
	return err
}

const markFailed = `-- name: MarkFailed :exec
UPDATE video_jobs
SET status = 'FAILED',
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkFailed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markFailed, id)
	return err
}

const markRetry = `-- name: MarkRetry :exec
UPDATE video_jobs
SET retry_count = retry_count + 1,
    next_retry_at = now() + ($1::int * interval '1 second'),
    status = 'PENDING',
    updated_at = now()
WHERE id = $2
`

type MarkRetryParams struct {
	Column1 int32
	ID      int64
}

func (q *Queries) MarkRetry(ctx context.Context, arg MarkRetryParams) error {
	_, err := q.db.Exec(ctx, markRetry, arg.Column1, arg.ID)
	return err
}
