// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countByStatus = `-- name: CountByStatus :many
SELECT status, COUNT(*) AS count
FROM video_jobs
GROUP BY status
`

type CountByStatusRow struct {
	Status string
	Count  int64
}

func (q *Queries) CountByStatus(ctx context.Context) ([]CountByStatusRow, error) {
	rows, err := q.db.Query(ctx, countByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountByStatusRow
	for rows.Next() {
		var i CountByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createJob = `-- name: CreateJob :one
INSERT INTO video_jobs (
    filename
) VALUES (
             $1
         )
    RETURNING id, filename, status, retry_count, next_retry_at, locked_at, locked_by, created_at, updated_at
`

func (q *Queries) CreateJob(ctx context.Context, filename string) (VideoJob, error) {
	row := q.db.QueryRow(ctx, createJob, filename)
	var i VideoJob
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Status,
		&i.RetryCount,
		&i.NextRetryAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOldDoneJobs = `-- name: DeleteOldDoneJobs :exec
DELETE FROM video_jobs
WHERE status = 'DONE'
  AND updated_at < now() - interval '7 days'
`

func (q *Queries) DeleteOldDoneJobs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldDoneJobs)
	return err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, filename, status, retry_count, next_retry_at, locked_at, locked_by, created_at, updated_at
FROM video_jobs
WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id int64) (VideoJob, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i VideoJob
	err := row.Scan(
		&i.ID,
		&i.Filename,
		&i.Status,
		&i.RetryCount,
		&i.NextRetryAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const jobExists = `-- name: JobExists :one
SELECT EXISTS (
    SELECT 1 FROM video_jobs WHERE id = $1
) AS exists
`

func (q *Queries) JobExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, jobExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockAndMarkProcessing = `-- name: LockAndMarkProcessing :many
UPDATE video_jobs
SET status    = 'PROCESSING',
    locked_at = now(),
    locked_by = $1
WHERE id IN (
    SELECT id
    FROM video_jobs
    WHERE status = 'PENDING'
      AND (next_retry_at IS NULL OR next_retry_at <= now())
    ORDER BY created_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
            )
            RETURNING id, filename, status, retry_count, next_retry_at, locked_at, locked_by, created_at, updated_at
`

type LockAndMarkProcessingParams struct {
	LockedBy pgtype.Text
	Limit    int32
}

func (q *Queries) LockAndMarkProcessing(ctx context.Context, arg LockAndMarkProcessingParams) ([]VideoJob, error) {
	rows, err := q.db.Query(ctx, lockAndMarkProcessing, arg.LockedBy, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideoJob
	for rows.Next() {
		var i VideoJob
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Status,
			&i.RetryCount,
			&i.NextRetryAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDone = `-- name: MarkDone :exec
UPDATE video_jobs
SET status    = 'DONE',
    locked_at = NULL,
    locked_by = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkDone(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markDone, id)
	return err
}

const markFailed = `-- name: MarkFailed :exec
UPDATE video_jobs
SET status    = 'FAILED',
    locked_at = NULL,
    locked_by = NULL,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkFailed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markFailed, id)
	return err
}

const markRetry = `-- name: MarkRetry :exec
UPDATE video_jobs
SET retry_count   = retry_count + 1,
    next_retry_at = now() + ($1::int * interval '1 second'),
    status        = 'PENDING',
    locked_at     = NULL,
    locked_by     = NULL,
    updated_at    = now()
WHERE id = $2
`

type MarkRetryParams struct {
	Column1 int32
	ID      int64
}

func (q *Queries) MarkRetry(ctx context.Context, arg MarkRetryParams) error {
	_, err := q.db.Exec(ctx, markRetry, arg.Column1, arg.ID)
	return err
}

const resetStuckJobs = `-- name: ResetStuckJobs :exec
UPDATE video_jobs
SET status    = 'PENDING',
    locked_at = NULL,
    locked_by = NULL,
    updated_at = now()
WHERE status = 'PROCESSING'
  AND locked_at < now() - interval '10 minutes'
`

func (q *Queries) ResetStuckJobs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, resetStuckJobs)
	return err
}
